### ISSUE TITLE
Shown changes differ between dash and editor

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris-dashboard#12]
https://dashboard.lutris.net/#/installers/submissions/23297

![Screenshot from 2019-03-31 20-16-19](https://user-images.githubusercontent.com/15083452/55301535-0d30be00-53f2-11e9-84c1-7884ad2a81ed.png)

https://lutris.net/games/resident-evil-revelations-bio-steam/installer/edit

![Screenshot from 2019-03-31 20-17-02](https://user-images.githubusercontent.com/15083452/55301536-0d30be00-53f2-11e9-8fe5-73a4b673db8f.png)

`lutris:resident-evil-revelations-biohazard-revelations-ue?revision=23297`

**Comment by AccountOneOff** [comment]
https://dashboard.lutris.net/#/installers/submissions/28381

Another busted one.

**Comment by strycore** [comment]
I haven't seen that in a while so I'll close it but I'll come up with a fix if I ever see that happen.
