### ISSUE TITLE
Allow to switch to line-only diff

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris-dashboard#15]
Garbage diffs such this one is unreadable mess and utterly useless to moderators:
![image](https://user-images.githubusercontent.com/10602045/58379590-36af3580-7fae-11e9-90a4-c1c18637a5f3.png)

**Comment by strycore** [comment]
The issue with newlines has been fixed and I also added a button to toggle per char diff, which makes the output more readable in some cases
