### ISSUE TITLE
Don't exit when accepting/removing submissions/drafts if there are still some available

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris-dashboard#17]
Once a submission/draft is accepted/deleted the page exits back to the submissions page. Instead, it should load another draft/submission if there are any available.

With the way it is now you have to review the installer, accept/delete installer, go back to game page, reload to refresh review button, and review the remaining edits. Repeat that process until there aren't any left.

It's tedious.

**Comment by strycore** [comment]
I removed the drafts from other users from the dropdown. Accepting a submission should have no effect on other people's work. There is a warning displayed when other people are working on the reviewed installer.
