### ISSUE TITLE
List of duplicates

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris-dashboard#25]
Since there's no way to report this from the website or /admin and strider doesn't always see it in the Discord I figured I'd open this ticket.

Game | Duplicate
|--------|-------------
|[Split/Second](https://lutris.net/games/splitsecond) | [Split/Second](https://lutris.net/games/split-second)
|[Final Fantasy XI](https://lutris.net/games/final-fantasy-xi) | [Final Fantasy XI Online](https://lutris.net/games/final-fantasy-xi-online/)
|[SpringRTS](https://lutris.net/games/springrts/) | [Spring WebLobby](https://lutris.net/games/spring-weblobby)
|[Sega Genesis & Mega Drive Classics](https://lutris.net/games/sega-genesis-mega-drive-classics/) |[Sega Genesis and Mega Drive Classics](https://lutris.net/games/sega-mega-drive-and-genesis-classics/)
|[Shin Megami Tensei: Persona 3](https://lutris.net/games/shin-megami-tensei-persona-3) | [Shin Megami Tensei: Persona 3 Portable](https://lutris.net/games/shin-megami-tensei-persona-3-portable/)
|[Neverwinter Nights](https://lutris.net/games/neverwinter-nights) | [Neverwinter Nights: Diamond](https://lutris.net/games/niverwinter-nights-diamond/)
|[Hitman 2](https://lutris.net/games/hitmantm-2/) | [Hitman 2](https://lutris.net/games/hitman-2/)
|[Wadanohara and the Great Blue Sea](https://lutris.net/games/wadanohara-and-the-great-blue-sea/) | [Wadanohara and the Great Blue Sea](https://lutris.net/games/wadanohara/)
|[Solus Stunts](https://lutris.net/games/solus-stunts/) | [Solus Stunts HugeGameArtGD](https://lutris.net/games/solus-stunts-hugegameartgd/)
[GTA V](https://lutris.net/games/grand-theft-auto-v) | [FiveM](https://lutris.net/games/fivem)
[Pokemon Revolution Online](https://lutris.net/games/pokemon-revolution-online) | [Pokemon Revolution Online (new version)](https://lutris.net/games/pokemon-revolution-online-new-version)
[Warface](https://lutris.net/games/warface) | [Warface_RU](https://lutris.net/games/warface_ru/)
[Kogama](https://lutris.net/games/kogama) | [Kogama Brasil](https://lutris.net/games/kogama-brasil/)
[Disgaea 5 Complete](https://lutris.net/games/disgaea-5-complete) | [Disgaea 5 Alliance of Vengeance](https://lutris.net/games/disgaea-5-alliance-of-vengeance/)

Sega Genesis & Mega Drive Classics has the wrong name but I can't change it until the dupe is deleted.

**Comment by strycore** [comment]
Use the merge tool in the dashboard to get rid of duplicates.
