### ISSUE TITLE
Add an action between Accept and Reject

### ISSUE THREAD

**Issue by smichel17** [lutris/lutris-dashboard#26]
While some installers should be rejected outright (piracy, shady sources, etc), more often I want to follow up with the submitter and and questions or request changes.

For example, recently someone submitted an installer for GOG's *Windows* version of [Another World](https://lutris.net/games/another-world/). There is already an installer for GOG's native version, so our policy is not to accept the Windows version in that scenario… unless it has features that the native one lacks. So in this case, rather than reject outright, I'd like to ask the submitter why they wanted the Windows version when the native one already exists. Otherwise I have to choose between accepting an unnecessary installer, rejecting a useful installer, or doing the work of researching why the Windows installer may be needed (In this case I chose to do nothing, and someone else accepted the installer later, so the [submission](https://dashboard.lutris.net/#/installers/submissions/55098) is no longer available).

It would be nice to have a third option, something like "Reject with reason" or "Request information/changes", that allows moderators to send a message to submitters and preserves the installer. The message could be sent through email or appear on the submitter's dashboard; the submission could either be included in the message or set back to draft status.

**Comment by strycore** [comment]
We're not adding a 3rd choice, this is bad design. There is either accept or reject. Once we have a notification system on the website, it will be easy to add but currently we don't have one.

**Comment by smichel17** [comment]
This is taking the request too literally. It doesn't need to be a third separate button, it can be an optional Reason field.

**Comment by tannisroot** [comment]
> We're not adding a 3rd choice, this is bad design. There is either accept or reject. Once we have a notification system on the website, it will be easy to add but currently we don't have one.

It's a bad design to only be able to reject a perfectly reasonable installer that just needs a few adjustments from the creator.
WineHQ's AppDB has the same issue and it is annoying as hell to waste time on a report only for it to be rejected due to some minor issue that you could have fixed in a few minutes.
