### ISSUE TITLE
external links: Fandom

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris-dashboard#29]
https://feral-wildworks.fandom.com/wiki/Feral is a nice wiki site for games informations, could it be possible to add it in external links choice?

**Comment by strycore** [comment]
that seems to be related to the website and not the moderation dashboard.

**Comment by legluondunet** [comment]
could you give me authorizations to create issue on website please.

**Comment by strycore** [comment]
It needs a patch on the website, the list is still hardcoded.

**Comment by strycore** [comment]
if you look for something like "Wikipedia" in the source, you'll find it, it's not hard to make that patch

**Comment by legluondunet** [comment]
I can try but remember that I have very basic development knowledge, I have skills to write Lutris or linux bash scripts, not more. 
But I will try.
