### ISSUE TITLE
Sort new installer submissions by submission date

### ISSUE THREAD

**Issue by smichel17** [lutris/lutris-dashboard#31]
Currently, installer _updates_ are sorted by submission date (most recent first, to form a LIFO queue). However, _new_ installers are sorted alphabetically. Most of the current first page of submissions has something that makes them hard to approve for one reason or another (and I do not want to reject them; see #26), so this view is basically useless at the moment :(

**Comment by strycore** [comment]
I'm deploying a patch that will order new installers by date and hide drafts from the list.
