### ISSUE TITLE
Diffs are kinda fucked 

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris-dashboard#35]
The `installer:` line is not actually there in the submission at the bottom, but it's shown like it's added there
![image](https://user-images.githubusercontent.com/10602045/142730934-915186ce-06cf-47a7-8360-adfee58b84b4.png)

**Comment by strycore** [comment]
Without a link to the broken installer, I can't work on that

**Comment by tannisroot** [comment]
I will see if I find another installer that has a similar issue

**Comment by tannisroot** [comment]
Found one:
https://dashboard.lutris.net/#/installers/submissions/70091
Notice how the battleye line is repeated in the diff even though in the actual change there's just one:
![image](https://user-images.githubusercontent.com/10602045/145688042-c2c2d675-5957-4a24-a751-956beb865eef.png)

**Comment by tannisroot** [comment]
This one is super weird too:
https://dashboard.lutris.net/#/installers/submissions/70743
![image](https://user-images.githubusercontent.com/10602045/145688680-e38cb875-1486-4e09-9849-7a2ee93c2d7f.png)
It gets cut off, even though there are more changes:
![image](https://user-images.githubusercontent.com/10602045/145688667-113e8697-b115-4bc9-b3e5-ed0de66c3732.png)

**Comment by strycore** [comment]
This installer no longer exists
