### ISSUE TITLE
Dashboard: every line has a diff

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris-dashboard#4]
This happens sometimes for whatever reason (the installer on the screenshot if for LoL)? I have no idea how and why.
![screenshot from 2019-02-25 07-12-37](https://user-images.githubusercontent.com/10602045/53313959-ddf7d000-38cc-11e9-95b5-41e19bc6f601.png)

**Comment by tannisroot** [comment]
This is still present if I edit an old installer, actually.

**Comment by strycore** [comment]
yeah, I noticed that as well on some installers, I'll give it another look when I reproduce it locally
