### ISSUE TITLE
Increase limit on listed items or add pages for drafts/submissions

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris-dashboard#6]
The lists are limited to 10 items and that's too little.

![screenshot_2019-02-25 lutris moderation](https://user-images.githubusercontent.com/15083452/53388179-0ddfbb80-393f-11e9-9a55-468ec8986623.png)

**Comment by strycore** [comment]
This shouldn't be needed, drafts are going to be auto-deleted soon and all submissions should be treated so I don't see the need to present more info

**Comment by tannisroot** [comment]
PLEASE increase it. This limit is so fucking dumb I want to blow my brains out.

**Comment by tannisroot** [comment]
You're not going to accomplish anything by forcing moderators to do stuff with such dumb methods, never ever.

**Comment by strycore** [comment]
pagination in the API bumped to 25 items by default

**Comment by strycore** [comment]
Fixed
