### ISSUE TITLE
Whole installer got turned into a single diff

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris-dashboard#9]
https://dashboard.lutris.net/#/installers/submissions/21787
![screenshot from 2019-03-02 00-19-12](https://user-images.githubusercontent.com/10602045/53667026-d9db0200-3c80-11e9-8e81-8c9e87a0c24d.png)
![screenshot from 2019-03-02 00-19-24](https://user-images.githubusercontent.com/10602045/53667029-db0c2f00-3c80-11e9-8782-6ea18bbde2e8.png)

**Comment by strycore** [comment]
closing as a likely duplicate of #16 (and the installer is gone)
